FROM nginx:latest

# Establece el directorio de trabajo en Nginx
#path /usr/share/nginx/html
WORKDIR /usr/share/nginx/html

# Copia todo el contenido de tu proyecto al directorio de Nginx
COPY . /usr/share/nginx/html/