[build]
  base    = "Angular-router"  # Asegúrate de estar dentro de la carpeta Angular-router
  command = "npx ng build --configuration production"  # Usamos npx para ejecutar ng localmente
  publish = "Angular-router/dist/my-store-router"  # La carpeta de salida de Angular

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
